version: "3.7"

services:
  ck-games-prod:
    container_name: ck-games-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 9000:9000
