# build env
FROM node:14-alpine as ck-games-builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --global gatsby-cli@3.8.0 && gatsby telemetry --disable
RUN npm install

COPY . .

RUN gatsby build


FROM nginx as server

EXPOSE 80

COPY --from=ck-games-builder /usr/src/app/public /usr/share/nginx/html

